-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mine` DEFAULT CHARACTER SET latin1 ;
USE `mine` ;

-- -----------------------------------------------------
-- Table `mine`.`chargeuse_bourrage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`chargeuse_bourrage` (
  `longueur_trou` DOUBLE NOT NULL COMMENT '',
  `DIAMETRE_TROU` DOUBLE NOT NULL COMMENT '',
  `BANQUETTE` DOUBLE NOT NULL COMMENT '',
  `ESPACEMENT` DOUBLE NOT NULL COMMENT '',
  `NOMBRE_TROU` INT(11) NOT NULL COMMENT '',
  `NOMBRE_RANGE` INT(11) NOT NULL COMMENT '',
  `NOMBRE_TROU_RANGE` INT(11) NOT NULL COMMENT '',
  `longueur_BOURRAGE_INTERMEDIAIRE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `ID_CHARGEUSE_BOURRAGE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_RESULTAT_CHARGEUSE_BOURRAGE` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_CHARGEUSE_BOURRAGE`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_RESULTAT_CHARGEUSE_BOURRAGE` ON `mine`.`chargeuse_bourrage` (`ID_RESULTAT_CHARGEUSE_BOURRAGE` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`chargeuse_continu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`chargeuse_continu` (
  `id_chargeuse_continu` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `longueur_trou` DOUBLE NOT NULL COMMENT '',
  `DIAMETRE_TROU` DOUBLE NOT NULL COMMENT '',
  `BANQUETTE` DOUBLE NOT NULL COMMENT '',
  `ESPACEMENT` DOUBLE NOT NULL COMMENT '',
  `NOMBRE_TROU` INT(11) NOT NULL COMMENT '',
  `NOMBRE_RANGE` INT(11) NOT NULL COMMENT '',
  `NOMBRE_TROU_RANGE` INT(11) NOT NULL COMMENT '',
  `ID_RESULTAT_CHARGEUSE_CONTINU` INT(11) NULL DEFAULT NULL COMMENT '',
  `ID_DETONNATEUR` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_chargeuse_continu`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_RESULTAT_CHARGEUSE_CONTINU` ON `mine`.`chargeuse_continu` (`ID_RESULTAT_CHARGEUSE_CONTINU` ASC)  COMMENT '';

CREATE INDEX `ID_DETONNATEUR` ON `mine`.`chargeuse_continu` (`ID_DETONNATEUR` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`detonnateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`detonnateur` (
  `ID_DETONNATEUR` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NUMERO` INT(11) NULL DEFAULT NULL COMMENT '',
  `RETARD` TIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_DETONNATEUR`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mine`.`explosif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`explosif` (
  `ID_EXPLOSIF` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `QUALITE` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `QUANTITE` INT(11) NULL DEFAULT NULL COMMENT '',
  `COULEUR` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `ID_PLAN` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_EXPLOSIF`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_PLAN` ON `mine`.`explosif` (`ID_PLAN` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`parametre_camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`parametre_camion` (
  `TEFF_TRAVAIL_CAMION` INT(11) NULL DEFAULT NULL COMMENT '',
  `TEMPS_CYCLE_CAMION` INT(11) NULL DEFAULT NULL COMMENT '',
  `COEF_REMPLISSAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_FOISONNEMENT` DOUBLE NULL DEFAULT NULL COMMENT '',
  `DENSITE_MATERIAUX` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NBRE_HEURE_TRAVAIL_JOUR` INT(11) NULL DEFAULT NULL COMMENT '',
  `NBRE_JOUR_TRAVAIL_MOIS` INT(11) NULL DEFAULT NULL COMMENT '',
  `NBRE_JOUR_TRAVAIL_AN` INT(11) NULL DEFAULT NULL COMMENT '',
  `FACTEUR_CONDUITE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `CAPACITE_NOMINALE_CAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `VOLUME_GODET_PELLE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_UTILISATION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `FACTEUR_EXPERIENCE_OPERATEUR` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_IRREGULARITE_PRODUCTION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `ID_PARAMETRE_CAMION` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_RESULTAT_CAMION` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_PARAMETRE_CAMION`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_RESULTAT_CAMION` ON `mine`.`parametre_camion` (`ID_RESULTAT_CAMION` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`parametre_chargeuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`parametre_chargeuse` (
  `TEFF_TRAVAIL_CHARGEUSE` INT(11) NULL DEFAULT NULL COMMENT '',
  `TEMPS_CYCLE_CHARGEUSE` INT(11) NULL DEFAULT NULL COMMENT '',
  `COEF_REMPLISSAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_FOISONNEMENT` DOUBLE NULL DEFAULT NULL COMMENT '',
  `DENSITE_MATERIAUX` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NBRE_HEURE_TRAVAIL_JOUR` INT(11) NULL DEFAULT NULL COMMENT '',
  `NBRE_JOUR_TRAVAIL_MOIS` INT(11) NULL DEFAULT NULL COMMENT '',
  `NBRE_JOUR_TRAVAIL_AN` INT(11) NULL DEFAULT NULL COMMENT '',
  `FACTEUR_CONDUITE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `VOLUME_GODET_PELLE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_UTILISATION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `FACTEUR_EXPERIENCE_OPERATEUR` DOUBLE NULL DEFAULT NULL COMMENT '',
  `COEF_IRREGULARITE_PRODUCTION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_CAMION` INT(11) NULL DEFAULT NULL COMMENT '',
  `ID_PARAMETRE_CHARGEUSE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_RESULTAT_CHARGEUSE` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_PARAMETRE_CHARGEUSE`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_RESULTAT_CHARGEUSE` ON `mine`.`parametre_chargeuse` (`ID_RESULTAT_CHARGEUSE` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`plan` (
  `ID_PLAN` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TYPE_PLAN` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `ID_RESULTAT_CHARGEUSE_CONTINU` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_PLAN`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_RESULTAT_CHARGEUSE_CONTINU` ON `mine`.`plan` (`ID_RESULTAT_CHARGEUSE_CONTINU` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`representation_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`representation_plan` (
  `ID_REPRESENTATION` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TYPE_REPRESENTATION` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `ID_PLAN` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_REPRESENTATION`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `ID_PLAN` ON `mine`.`representation_plan` (`ID_PLAN` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mine`.`resultat_camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`resultat_camion` (
  `NOMBRE_GODET_CAMION` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `TONNAGE_MATERIAUX_CAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_CYCLE_JOUR` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CAMION_JOUR` DOUBLE NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CAMION_MOIS` DOUBLE NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CAMION_AN` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_JOURNALIERE_CAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_JOURNALIERE_NCAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_MENSUEL_CAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_MENSUEL_NCAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_ANNUELLE_CAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_ANNUELLE_NCAMION` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_JOURNALIERE_CARRIERE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_MENSUEL_CARRIERE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_ANNUELLE_CARRIERE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `ID_RESULTAT_CAMION` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`ID_RESULTAT_CAMION`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mine`.`resultat_chargeuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`resultat_chargeuse` (
  `NOMBRE_CYCLE_CHARGEUSE` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CHARGEUSE_JOUR` DOUBLE NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CHARGEUSE_MOIS` DOUBLE NULL DEFAULT NULL COMMENT '',
  `RENDEMENT_CHARGEUSE_AN` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_JOURNALIERE_CHARGEUSE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_MENSUEL_CHARGEUSE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `PRODUCTION_ANNUELLE__CHARGEUSE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `ID_RESULTAT_CHARGEUSE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`ID_RESULTAT_CHARGEUSE`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mine`.`resultat_chargeuse_bourrage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`resultat_chargeuse_bourrage` (
  `longueur_BOURRAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `MAILLE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `CUBAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `TONNAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `LONGUEUR_TOTAL_FOREE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `LONGUEUR_CHARGE_PIED` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_GOMME` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_GOMME_CARTON` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `NOMBRE_SAC_NITRATE_TROU` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `CHARGE_UNITAIRE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `CHARGE_SPECIFIQUE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_CARTON_CORDEAU_DETONANT` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `MASSE_TOTAL_NITRATE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `MASSE_TOTAL_GOMME` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_SAC_NITRATE` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `ID_RESULTAT_CHARGEUSE_BOURRAGE` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `LONGUEUR_CHARGE_FONT` DOUBLE NULL DEFAULT NULL COMMENT '',
  `LONGUEUR_RELANCE_CHARGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_RESULTAT_CHARGEUSE_BOURRAGE`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mine`.`resultat_chargeuse_continu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mine`.`resultat_chargeuse_continu` (
  `ID_RESULTAT_CHARGEUSE_CONTINU` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `longueur_BOURRAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `MAILLE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `CUBAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `TONNAGE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `LONGUEUR_TOTAL_FOREE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `LONGUEUR_CHARGE_PIED` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_GOMME` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_GOMME_CARTON` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `NOMBRE_SAC_NITRATE_TROU` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `NOMBRE_TOTAL_SAC_NITRATE` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `CHARGE_UNITAIRE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `CHARGE_SPECIFIQUE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `NOMBRE_CARTON_CORDEAU_DETONANT` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `MASSE_TOTAL_NITRATE` DOUBLE NULL DEFAULT NULL COMMENT '',
  `MASSE_TOTAL_GOMME` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_RESULTAT_CHARGEUSE_CONTINU`)  COMMENT '')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
